In [1]:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.


In [5]:
env.close()

In [21]:
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
            

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.00056963  0.02624063  0.03780582 -0.02406667]
[ 0.00109444  0.22080059  0.03732449 -0.30458581]
[ 0.00551046  0.02516716  0.03123277 -0.00036919]
[ 0.0060138   0.21982759  0.03122539 -0.28303648]
[0.01041035 0.02427449 0.02556466 0.01932893]
[ 0.01089584 -0.17120458  0.02595124  0.31996692]
[0.00747175 0.02353836 0.03235058 0.03557968]
[ 0.00794252 -0.17203221  0.03306217  0.33829146]
[0.00450187 0.02260406 0.039828   0.05621512]
[ 0.00495395  0.21713297  0.0409523  -0.22364052]
[0.00929661 0.02145036 0.03647949 0.08167391]
[ 0.00972562 -0.17417502  0.03811297  0.38563935]
[ 0.00624212 -0.36981672  0.04582576  0.69009129]
[-0.00115421 -0.56554363  0.05962758  0.99684149]
[-0.01246509 -0.37126751  0.07956441  0.72346533]
[-0.01989044 -0.56739448  0.09403372  1.04009236]
[-0.03123833 -0.37363906  0.11483557  0.77834842]
[-0.03871111 -0.57013699  0.13040254  1.1048415 ]
[-0.05011385 -0.7

[ 0.03893431 -0.19113557 -0.01194793  0.30228212]
[ 0.0351116   0.00415461 -0.00590229  0.00585515]
[ 0.03519469  0.19936071 -0.00578519 -0.28868416]
[ 0.03918191  0.39456468 -0.01155887 -0.58318605]
[ 0.0470732   0.58984664 -0.02322259 -0.87948766]
[ 0.05887013  0.78527629 -0.04081235 -1.17937992]
[ 0.07457566  0.59070733 -0.06439994 -0.899765  ]
[ 0.08638981  0.78664011 -0.08239525 -1.21197544]
[ 0.10212261  0.59267268 -0.10663475 -0.94620816]
[ 0.11397606  0.78905662 -0.12555892 -1.27040209]
[ 0.12975719  0.59574115 -0.15096696 -1.01952901]
[ 0.14167202  0.40291815 -0.17135754 -0.77780011]
[ 0.14973038  0.59992998 -0.18691354 -1.1191227 ]
[ 0.16172898  0.40768533 -0.20929599 -0.89041153]
Episode finished after 15 timesteps
[-0.04793429  0.00503317 -0.01904642 -0.02991799]
[-0.04783363 -0.18981054 -0.01964478  0.25669525]
[-0.05162984 -0.38464659 -0.01451088  0.54311774]
[-0.05932277 -0.18932375 -0.00364852  0.24589827]
[-0.06310924 -0.3843934   0.00126944  0.53742814]
[-0.07079711 -

[-0.07279803 -0.23049715 -0.00957022  0.12657943]
[-0.07740797 -0.4254807  -0.00703863  0.41622776]
[-0.08591758 -0.2302597   0.00128593  0.12133419]
[-0.09052278 -0.42540006  0.00371261  0.41442253]
[-0.09903078 -0.23033092  0.01200106  0.12291235]
[-0.1036374  -0.03538295  0.01445931 -0.16596033]
[-0.10434506 -0.23070886  0.0111401   0.1312488 ]
[-0.10895923 -0.03574824  0.01376508 -0.15789885]
[-0.1096742  -0.23106454  0.0106071   0.13909464]
[-0.11429549 -0.42633679  0.01338899  0.43510497]
[-0.12282223 -0.23140692  0.02209109  0.14667262]
[-0.12745036 -0.03660817  0.02502454 -0.13895995]
[-0.12818253 -0.23207944  0.02224534  0.16151159]
[-0.13282412 -0.0372829   0.02547558 -0.12407134]
[-0.13356977  0.15746499  0.02299415 -0.40860937]
[-0.13042047  0.3522535   0.01482196 -0.69395521]
[-0.1233754   0.15692911  0.00094286 -0.39664331]
[-0.12023682  0.35203767 -0.00699001 -0.68902883]
[-0.11319607  0.54725593 -0.02077058 -0.98390411]
[-0.10225095  0.35241831 -0.04044867 -0.69781683]


In [22]:
env.close()

In [8]:
env = gym.make('CartPole-v0')
print(env.action_space)

print(env.observation_space)


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Discrete(2)
Box(4,)


In [9]:
print(env.observation_space.high)

print(env.observation_space.low)

[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38]
[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38]


In [13]:
from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8
x

2

In [17]:
import time

In [26]:
env = gym.make('CartPole-v0')
observation = env.reset()
for i in range(10):
    env.render()
    time.sleep(1)
    print(observation)
    observation, reward, done, info = env.step(1)
    if done:
        break
env.close()
# 0 is left, 1 is right

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
[ 0.00855854 -0.01366441 -0.01044383  0.04042764]
[ 0.00828526  0.18160574 -0.00963528 -0.25553204]
[ 0.01191737  0.37686392 -0.01474592 -0.55123845]
[ 0.01945465  0.57218984 -0.02577069 -0.84853062]
[ 0.03089845  0.76765362 -0.0427413  -1.14920468]
[ 0.04625152  0.96330661 -0.0657254  -1.45497825]
[ 0.06551765  1.15917098 -0.09482496 -1.76744982]
[ 0.08870107  1.35522755 -0.13017396 -2.08805027]
[ 0.11580562  1.55140136 -0.17193496 -2.41798449]
